// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FigmaSharp.Samples
{
	public partial class DocumentWindow : NSWindow
	{
		public DocumentWindow (IntPtr handle) : base (handle)
		{
		}
	}
}
