// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;

using AppKit;
using CoreGraphics;
using Foundation;

namespace FigmaSharp.Samples
{
    public partial class DocumentWindowController : NSWindowController
    {
        public DocumentWindowController(IntPtr handle) : base(handle)
        {
        }


        public static int WindowCount { get; private set; }

        public string test;




        public override void WindowDidLoad()
        {

            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 1"));
            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 2"));
            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 3"));
            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 4"));
            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 5"));

            PagePopUpButton.Activated += delegate {
                Console.WriteLine(PagePopUpButton.SelectedItem.Title);
            };





            WindowCount++;

            int offset = 38;

            CGRect frame = Window.Frame;
            frame.X += offset * WindowCount;
            frame.Y -= offset * WindowCount;
            Window.SetFrame (frame, display: true);


            base.WindowDidLoad();
        }


        public void ConfigureDocument(string token, string link_id)
        {
            TitleTextField.StringValue = string.Format("Opening “{0}”…", link_id);

            (Window.ContentViewController as DocumentViewController).Token = token;
            (Window.ContentViewController as DocumentViewController).Link_ID = link_id;
        }


        partial void RefreshClicked(NSObject sender)
        {
            if (MainToolbar.VisibleItems[1].Identifier != "RefreshSpinner") {
                MainToolbar.InsertItem("RefreshSpinner", 1);
               (MainToolbar.VisibleItems[1].View as NSProgressIndicator).StartAnimation(this);
            
            } else {
                (MainToolbar.VisibleItems[1].View as NSProgressIndicator).StopAnimation(this);
                MainToolbar.RemoveItem(1);
            }

           // RefreshSpinner.View.Hidden = true;
           //RefreshSpinner.
            (Window.ContentViewController as DocumentViewController).Reload();
        }
    }
}
