// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;

using AppKit;
using CoreGraphics;

namespace FigmaSharp.Samples
{
    public partial class DocumentWindowController : NSWindowController
    {
        public DocumentWindowController(IntPtr handle) : base(handle)
        {
        }


        public static int WindowCount { get; private set; }

        public override void WindowDidLoad()
        {

            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 1"));
            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 2"));
            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 3"));
            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 4"));
            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 5"));

            PagePopUpButton.Activated += delegate {
                Console.WriteLine(PagePopUpButton.SelectedItem.Title);
            };

            RefreshButton.Activated += delegate {
                Console.WriteLine("Refresh clicked");
            };

            TitleTextField.StringValue = "Opening “DhOTs1gwx837ysnG3X6RZqZm”…";

            Console.WriteLine ((Window.ContentViewController as DocumentViewController).test);

            WindowCount++;

            int offset = 38;

            CGRect frame = Window.Frame;
            frame.X += offset * WindowCount;
            frame.Y -= offset * WindowCount;
            Window.SetFrame (frame, display: true);

            base.WindowDidLoad();

            /*
            var alert = new NSAlert()
            {
                AlertStyle = NSAlertStyle.Warning,
                MessageText = "Could not open “DhOTs1gwx837ysnG3X6RZqZm”",
                InformativeText = "Please check if your Figma Link and Personal Access Token are correct",
            };

            alert.AddButton("Close");
            alert.RunSheetModal(Window);
            */           
        }
    }
}
