// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;

using Foundation;
using AppKit;

namespace FigmaSharp.Samples
{
    public partial class MyWindowController : NSWindowController
    {

        public MyWindowController (IntPtr handle) : base (handle)
        {
        }


        public override void WindowDidLoad()
        {
            base.WindowDidLoad();

            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 1"));
            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 2"));
            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 3"));
            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 4"));
            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 5"));

            PagePopUpButton.Activated += delegate {
                Console.WriteLine(PagePopUpButton.SelectedItem.Title);
            };

            RefreshButton.Activated += delegate {
                Console.WriteLine("Refresh clicked");
            };

            TitleTextField.StringValue = "Opening “DhOTs1gwx837ysnG3X6RZqZm”…";

            var menu = new VersionMenu();
            menu.AddItem("1", "FigmaSharp.Cocoa 0.0.1", DateTime.Now); ;
            menu.AddItem("2", "FigmaSharp.Cocoa 0.0.2", DateTime.Now); ;
            menu.AddItem("3", "FigmaSharp.Cocoa 0.0.3", DateTime.Now); ;
            menu.AddItem("4", DateTime.Now);
            menu.AddItem("5", DateTime.Now.AddDays(-7));
            menu.AddItem("6", DateTime.Now.AddDays(-14));
            menu.UseAsVersionsMenu();

            menu.VersionSelected += delegate (string id) {
                Console.WriteLine(id);
            };
        }
    }
}
