// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FigmaSharp.Samples
{
	public partial class MyWindowController : NSWindowController
	{

		public MyWindowController (IntPtr handle) : base (handle)
		{
        }


        public override void WindowDidLoad()
        {
            base.WindowDidLoad();

            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 1"));
            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 2"));
            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 3"));
            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 4"));
            PagePopUpButton.Menu.AddItem(new NSMenuItem("Page 5"));

            RefreshButton.Activated += delegate {
                Console.WriteLine("Refresh clicked");
            };

            TitleTextField.StringValue = "Opening “DhOTs1gwx837ysnG3X6RZqZm”…";
            (NSApplication.SharedApplication.MainMenu.Items[3] as NSMenuItem).Submenu.RemoveItemAt(0);
            (NSApplication.SharedApplication.MainMenu.Items[3] as NSMenuItem).Submenu.AddItem(new NSMenuItem("Current") { State = NSCellStateValue.On });

            (NSApplication.SharedApplication.MainMenu.Items[3] as NSMenuItem).Submenu.AddItem(NSMenuItem.SeparatorItem);

            (NSApplication.SharedApplication.MainMenu.Items[3] as NSMenuItem).Submenu.AddItem(new NSMenuItem("FigmaSharp.Cocoa 0.0.4"));
            (NSApplication.SharedApplication.MainMenu.Items[3] as NSMenuItem).Submenu.AddItem(new NSMenuItem("FigmaSharp.Cocoa 0.0.3"));
            (NSApplication.SharedApplication.MainMenu.Items[3] as NSMenuItem).Submenu.AddItem(new NSMenuItem("FigmaSharp.Cocoa 0.0.2"));
            (NSApplication.SharedApplication.MainMenu.Items[3] as NSMenuItem).Submenu.AddItem(new NSMenuItem("FigmaSharp.Cocoa 0.0.1"));

            (NSApplication.SharedApplication.MainMenu.Items[3] as NSMenuItem).Submenu.AddItem(NSMenuItem.SeparatorItem);
            (NSApplication.SharedApplication.MainMenu.Items[3] as NSMenuItem).Submenu.AddItem(new NSMenuItem("History") { Enabled = false });
            (NSApplication.SharedApplication.MainMenu.Items[3] as NSMenuItem).Submenu.AddItem(new NSMenuItem("Sat 6 July at 11:13, 2019"));
            (NSApplication.SharedApplication.MainMenu.Items[3] as NSMenuItem).Submenu.AddItem(new NSMenuItem("Sat 6 July at 11:13, 2019"));
            (NSApplication.SharedApplication.MainMenu.Items[3] as NSMenuItem).Submenu.AddItem(new NSMenuItem("Sat 6 July at 11:13, 2019"));
            (NSApplication.SharedApplication.MainMenu.Items[3] as NSMenuItem).Submenu.AddItem(new NSMenuItem("Sat 6 July at 11:13, 2019"));
            (NSApplication.SharedApplication.MainMenu.Items[3] as NSMenuItem).Submenu.AddItem(new NSMenuItem("Sat 6 July at 11:13, 2019"));

        }
    }
}
