// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FigmaSharpApp
{
	public partial class WarningsView : NSView
	{
		public WarningsView (IntPtr handle) : base (handle)
		{
		}
	}
}
