// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FigmaSharp.Samples
{
	public partial class CodeWindowController : NSWindowController
	{
		public CodeWindowController (IntPtr handle) : base (handle)
		{
		}
	}
}
