// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace StandaloneDesigner
{
	public partial class ContentScrollView : NSScrollView
	{
		public ContentScrollView (IntPtr handle) : base (handle)
		{
		}
    }
}
