// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FigmaSharp.Samples
{
	public partial class OpenLocationSegue : NSButton
	{
		public OpenLocationSegue (IntPtr handle) : base (handle)
		{
		}
	}
}
